version: '3'

networks:
  overlay-cluster:
    external: true


services:



  redis-master2:
    container_name: redis-master2
    image: redis:4.0.13-ruby
    restart: unless-stopped
    hostname: redis-master2
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 6380:6379
      - 16380:16379
    command:
      - "redis-server"
      - "/home/redis/cluster/redis.conf"
    volumes:
      - ../image/redis-trib.rb:/usr/bin/redis-trib.rb
      - ../image/redis-master2.conf:/home/redis/cluster/redis.conf
      - /data/redisdata/redis-master2:/data
    networks:
      - overlay-cluster

  redis-master3:
    container_name: redis-master3
    image: redis:4.0.13-ruby
    restart: unless-stopped
    hostname: redis-master3
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 6381:6379
      - 16381:16379
    command:
      - "redis-server"
      - "/home/redis/cluster/redis.conf"
    volumes:
      - ../image/redis-trib.rb:/usr/bin/redis-trib.rb
      - ../image/redis-master3.conf:/home/redis/cluster/redis.conf
      - /data/redisdata/redis-master3:/data
    networks:
      - overlay-cluster


  redis-slave1:
    container_name: redis-slave1
    image: redis:4.0.13-ruby
    restart: unless-stopped
    hostname: redis-slave1
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 6382:6379
      - 16382:16379
    command:
      - "redis-server"
      - "/home/redis/cluster/redis.conf"
    volumes:
      - ../image/redis-trib.rb:/usr/bin/redis-trib.rb
      - ../image/redis-slave1.conf:/home/redis/cluster/redis.conf
      - /data/redisdata/redis-slave1:/data
    networks:
      - overlay-cluster

